language: node_js
node_js:
- '4.0'
addons:
  apt:
    packages:
    - lynx

before_install:
  - curl -sSL https://raw.githubusercontent.com/robisonsantos/evm/master/install | bash
  - source $HOME/.evm/scripts/evm

script:
  - evm list
