language: node_js
node_js:
- '4.0'

before_install:
  - git clone https://github.com/HashNuke/asdf.git ~/.asdf
  - source $HOME/.asdf/asdf.sh
  - asdf install erlang 17.3

script:
  - asdf which erlang
